### ISSUE TITLE
Oscillatory integral using the DE formula?

### ISSUE THREAD

**Issue by komatsu5147** [machakann/DoubleExponentialFormulas.jl#1]
Dear machakann,

I've just discovered your package on the DE integrator for Julia and love it! I am using it everywhere in my Julia codes now. 

I have a question: I wonder if you have an intention to include a DE integrator for an oscillatory integrand. 

This problem was solved by Prof. Ooura, who wrote [this paper](https://www.sciencedirect.com/science/article/pii/037704279190181I) with Prof. Mori. I attach the paper to this message for your convenience: [ooura-mori.pdf](https://github.com/machakann/DoubleExponentialFormulas.jl/files/4674202/ooura-mori.pdf)

He makes his codes available in [his website](http://www.kurims.kyoto-u.ac.jp/~ooura/intde.html), where we can find the codes in both C and fortran. 

Naively, one would just replace the weight function in your Julia code by phi(t) = (t+sqrt(t^2+exp(p-k*cosh(t))))/2. (Note that this is what is used in his code, as opposed to Eq.(11) in the above paper, phi(t) = t/(1-exp(-2*pi*sinh(t))).) 

What do you think?

Sincerely yours, komatsu5147

**Comment by machakann** [comment]
Thank you for the resources. It would be nice for real uses if this kind of variation was implemented.

It seems that there is also an updated equation in [Ooura, T., Mori, M., 1999. A robust double exponential formula for Fourier-type integrals. Journal of Computational and Applied Mathematics 112, 229–241.](https://doi.org/10.1016/S0377-0427(99)00223-X) I'm not sure which one is best but I will write something, at least, working soon. Let me check the resources first.

**Comment by komatsu5147** [comment]
Many thanks for your comment! Probably the best place to start is his codes (see the website in my first message) because he is probably using the best algorithm that is known to him.

**Comment by machakann** [comment]
Fair enough. Ok, everything is clear now.

**Comment by machakann** [comment]
Hi, I just have pushed the initial implementation of a numerical integrator for the decaying oscillatory integrands. In these commits, a new function `quaddeo` is added. It takes a decaying oscillatory integrand like `f(x) = g(x)*sin(ωx + θ)`. `g(x)` is a decaying function, `ω` and `θ` are the frequency and the phase of the oscillatory part of the integrands.

The interface is similar to `quadde` but it is required to specify `ω` and `θ`.

```
    quaddeo(f::Function, ω::Real, θ::Real, a::Real, b::Real;
            h0::Real=one(ω)/5, maxlevel::Integer=12,
            atol::Real=zero(ω),
            rtol::Real=atol>0 ? zero(atol) : sqrt(eps(typeof(atol))))
```

If the oscillatory part is `sin(ωx)`, then `θ = 0.0`; if it is `cos(ωx)` instead, then `θ = π/(2ω)`. An example of Dirichlet integral is here.

```julia
using DoubleExponentialFormulas
using LinearAlgebra

f(x) = sin(x)/x
ω = 1.0
θ = 0.0
I, E = quaddeo(f, ω, θ, 0.0, Inf)
I ≈ π/2
E ≤ sqrt(eps(typeof(I))*norm(I))
```

This is the initial implementation and not yet well-tested. Please inform me something wrong. For numerical stability, I may make change for future but hopefully it would be ignorable.

**Comment by komatsu5147** [comment]
Thanks sooo much!! I will use it and let you know if I find anything. 
Eiichiro

**Comment by komatsu5147** [comment]
I’ve tried quaddeo and it works beautifully!  
FYI: I am using it in https://github.com/komatsu5147/MatterPower.jl, highlighting your package. Thanks again. 
Eiichiro
